# Generated by Django 4.0.6 on 2022-08-16 17:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_quizattempt_score_quizattempt_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='attempt_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
